name:                curry-language-server
version:             0.1.0.0
github:              "fwcd/curry-language-server"
license:             BSD3
author:              "fwcd"
copyright:           "2020 fwcd"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fwcd/curry-language-server#readme>

dependencies:
  - base >= 4.12.0.0 && < 4.13
  - aeson >= 1.4.6.0 && < 1.5
  - containers >= 0.6.0.1 && < 0.7
  - data-default >= 0.7.1.1 && < 0.8
  - extra >= 1.6.18 && < 1.7
  - mtl >= 2.2.2 && < 2.3
  - transformers >= 0.5.6.2 && < 0.6
  - stm >= 2.5.0.0 && < 2.6
  - text >= 1.2.3.1 && < 1.3
  - lens >= 4.17.1 && < 4.18
  - hslogger >= 1.2.12 && < 1.3
  - filepath >= 1.4.2.1 && < 1.5
  - directory >= 1.3.3.0 && < 1.4
  - haskell-lsp >= 0.20.0.0 && < 0.21
  - bytestring >= 0.10.8.1 && < 0.11
  - bytestring-trie >= 0.2.5.0 && < 0.3
  - pretty >= 1.1.3.6 && < 1.2
  - curry-base == 1.2.0
  - curry-frontend == 2.0.0

library:
  source-dirs: src

executables:
  curry-language-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - curry-language-server

tests:
  curry-language-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - curry-language-server
